### ISSUE TITLE
Empty languages after installation

### ISSUE THREAD

**Issue by kaichaosun** [coasys/ad4m-cli#3]
Run `ad4m languages all`, result is `[]`.
Seems a few build-in languages should be installed automatically, but I got empty.

**Comment by kaichaosun** [comment]
This error seems failed into the empty langs, but i'm not sure why is ad4m-cli trying to find file in my local `ad4m-executor`? It actually depends on the where you run `ad4m serve.`
```
(node:18613) UnhandledPromiseRejectionWarning: Error: Error loading languages Error: ENOENT: no such file or directory, open '/Users/kaichaosun/github/holo/ad4m-executor/sr
c/builtin-langs/agent-expression-store/build/bundle.js'
    at LanguageController.loadLanguages (/Users/kaichaosun/.nvm/versions/node/v14.17.0/lib/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-executor/li
b/core/LanguageController.js:71:19)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async PerspectivismCore.initLanguages (/Users/kaichaosun/.nvm/versions/node/v14.17.0/lib/node_modules/@perspect3vism/ad4m-cli/node_modules/@perspect3vism/ad4m-execut
or/lib/core/PerspectivismCore.js:150:9)
    at async /Users/kaichaosun/.nvm/versions/node/v14.17.0/lib/node_modules/@perspect3vism/ad4m-cli/src/cli.js:97:7
(node:18613) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```

**Comment by kaichaosun** [comment]
Further finding it's because the network issue, if the language file is not able to download, the language is empty, also `agent generate` will panic in this scenario.
Better improve the error information when download language fails.

**Comment by jdeepee** [comment]
> Further finding it's because the network issue, if the language file is not able to download, the language is empty, also `agent generate` will panic in this scenario. Better improve the error information when download language fails.

Ha I also had this problem with Fayeed. The entanglement-proof PR on the ad4m-executor does some checking to see if the language is null and then returns a proper error if so.
